### ISSUE TITLE
userat is not correct

### ISSUE THREAD

**Issue by rbender23** [DMR-Database/database-tools#4]
Hello,

I tried the AnytoneFlashTool 2.00a to get an actual user DB for my 878, but I recognized, that the downloaded data are not actual and correct. If you compare the data with RadioID, the current database, some mismatched records come out. This is especially noticeable with reassigned ID's.

Kind regards/73
Ralf

**Comment by hb9gfx** [comment]
Today I updated my AT 868 and noticed the also the issue that some records are wrong. 
Example 2623050 should  be DL1YGFH but is DL0OSN what is wrong
67956,2623050,DL0OSN,Henning,Osnabrueck,Lower Saxony,Germany,,Private Call,None
correct is:
,2623050,DL1YGH,DL1YGH Matthias,Bielefeld,Nw,DEU,,Private Call,None (coming from another DB

There are many more of wrong records.

**Comment by PD1LOI** [comment]
> Hello,
> 
> I tried the AnytoneFlashTool 2.00a to get an actual user DB for my 878, but I recognized, that the downloaded data are not actual and correct. If you compare the data with RadioID, the current database, some mismatched records come out. This is especially noticeable with reassigned ID's.
> 
> Kind regards/73 Ralf

https://mega.nz/file/1zgnQSLS#95VXcWCpu7qmxyX6r9nhuFywBFGyLL_Ua85646H9mFQ New link
