### ISSUE TITLE
Not writing userdb

### ISSUE THREAD

**Issue by baxterdmutt** [DMR-Database/database-tools#5]
Will this software not work on devices that have the travisgoodspeed firmware. I try writing the userdb and nothing happens. It says that it’s flashing but the radio never shows that it is transferring data. I know the usb port works because I can put in the code plugs. Thanks.

**Comment by baxterdmutt** [comment]
I’ve gotten it to connect a few times but it doesn’t seem to write any contacts. In fact it screwed up the radio and it took several tries to get the radio back.

**Comment by javastraat** [comment]
oh man sorry that we screwed your ht
what ht do you use so i can test it 

sorry for the trouble

73 Einstein

**Comment by baxterdmutt** [comment]
It’s ok. I got it back using linux and the travisgoodspeed app. Then I tried restarting windows (again!) Then I installed your firmware (I think it’s the same as travis ) and that went well. So I tried the db again and it worked. It might have just been a strange windows issue. There is no shortage of those!

**Comment by javastraat** [comment]
lol
glad you got it back working. Yes the firmware is a daily build of travis firmware

if you have any issues let me know :0

73

**Comment by baxterdmutt** [comment]
Thank you. If it’s the software is the daily build of Travis software then I wonder why it would not write the firmware, yet the travis could. And then afterwards this one could. Is it likely to have just been a windows issue?

**Comment by baxterdmutt** [comment]
I realize you’ve closed this but I thought I should let you know that I tried in a different radio and the same thing happened. It looks like between erasing the only db on the radio and before starting the write, it disconnects and doesn’t want to reconnect. The radio shows it’s connected but the progress bar starts the second pass and stops right at the beginning never to start again. It takes 10 or so tries to get it to go all the way through.
