### ISSUE TITLE
User.cvs out of date

### ISSUE THREAD

**Issue by baxterdmutt** [DMR-Database/database-tools#6]
Hi,
Looking through the users.csv download and it is very very much out of date. I thought these were now updated regularly again, but my callsign location was edited in radioid.net well over a year ago and the DB still shows my old location.

**Comment by javastraat** [comment]
hi

so whats your call sign......
how do you think we can fix some thing without any info
or even look into it

and what is very very out of date ? we did a full pull, did you check the database or database-beta ?
if database check the last update date, and have a look at database-beta

**Comment by javastraat** [comment]
please post database problems in the correct github, this is for the tools only.

**Comment by baxterdmutt** [comment]
Va7vhRogerOn Jun 20, 2023, at 12:38, Albert Einstein ***@***.***> wrote:﻿
hi
so whats your call sign......

**Comment by javastraat** [comment]
https://github.com/DMR-Database/database-tools/issues/7

**Comment by javastraat** [comment]
fix via https://github.com/DMR-Database/database-tools/issues/7
